export const aiTools = [
  {
    name: "OpenAI ChatGPT",
    category: "Assistant",
    description: "General-purpose AI assistant for research, writing, coding, and workflow support.",
    url: "https://chatgpt.com",
    logo: "/tools/chatgpt.png",
  },
  {
    name: "Claude",
    category: "Reasoning",
    description: "Long-context assistant used for analysis, drafting, and product thinking.",
    url: "https://claude.ai",
    logo: "/tools/claude.png",
  },
  {
    name: "Perplexity",
    category: "Search",
    description: "Answer engine for cited web research and fast market scanning.",
    url: "https://www.perplexity.ai",
    logo: "/tools/perplexity.png",
  },
  {
    name: "Cursor",
    category: "Developer",
    description: "AI-native code editor for pair programming and repository-aware edits.",
    url: "https://cursor.com",
    logo: "/tools/cursor.png",
  },
  {
    name: "Runway",
    category: "Video",
    description: "Creative AI suite for video generation, editing, and visual experimentation.",
    url: "https://runwayml.com",
    logo: "/tools/runway.png",
  },
  {
    name: "ElevenLabs",
    category: "Audio",
    description: "Voice generation and speech tooling for narration, agents, and localization.",
    url: "https://elevenlabs.io",
    logo: "/tools/elevenlabs.png",
  },
  {
    name: "Midjourney",
    category: "Image",
    description: "High-quality image generation for concept art, campaigns, and visual direction.",
    url: "https://www.midjourney.com",
    logo: "/tools/midjourney.png",
  },
  {
    name: "Hugging Face",
    category: "Models",
    description: "Open model hub and deployment platform for machine learning teams.",
    url: "https://huggingface.co",
    logo: "/tools/huggingface.png",
  },
  {
    name: "Vercel AI SDK",
    category: "Framework",
    description: "TypeScript toolkit for building streaming AI interfaces and agents.",
    url: "https://sdk.vercel.ai",
    logo: "/tools/vercel-ai.png",
  },
  {
    name: "LangChain",
    category: "Agents",
    description: "Framework for composing retrieval, tool use, memory, and agent workflows.",
    url: "https://www.langchain.com",
    logo: "/tools/langchain.png",
  },
];
