[bastion]
mini-cloud-bastion ansible_host=localhost ansible_port=2222 ansible_user=devops ansible_password=devops ansible_python_interpreter=/usr/bin/python3

[kind_nodes]
mini-cloud-control-plane ansible_connection=community.docker.docker
mini-cloud-worker ansible_connection=community.docker.docker
mini-cloud-worker2 ansible_connection=community.docker.docker

[kind_nodes:vars]
ansible_python_interpreter=/usr/bin/python3
